version: '3.8'
services:
  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - "6379:6379"
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: my-redis-commander
    environment:
      - REDIS_HOSTS=my-redis
    ports:
      - "8081:8081"